config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'restaurants#index'
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy


  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: %w(chinese italian japanese french belgian)}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates :content, presence: true
  validates :rating, numericality: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
    @restaurant = Restaurant.find(params[:id])

  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to @restaurant

  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end



end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant

  def new
    @review = Review.new
  end

  def create
    @review = @restaurant.reviews.new(review_params)
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private
  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%=  render 'components/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
<%= f.input :name  %>
<%= f.input :address  %>
<%= f.input :category  %>
<%= f.input :phone_number  %>
<%= f.button :submit, class: "btn btn-primary"  %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

<%= link_to '<back to list', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Restaurants list</h1>

<%= link_to "➕ Add restaurant", new_restaurant_path %>

<% @restaurants.each do |restaurant| %>
  <h3>   <%= link_to restaurant.name, restaurant_path(restaurant) %> </h3>
  <p> <%= restaurant.category %> </p>
  <% end %>
  <hr>

app/views/restaurants/new.html.erb
<%=  render 'form' %>

app/views/restaurants/show.html.erb
<h1>Restaurant</h1>


<div class="container">
  <div class="links">
    <%= link_to "< back to list", restaurants_path %>
    <%= link_to "update restaurant", edit_restaurant_path(@restaurant) %>
    <%= link_to "new review", new_restaurant_review_path(@restaurant) %>
  </div>

  <div class="restaurant">
    <h1><%= @restaurant.name %></h1>
    <p><%= @restaurant.category %></p>
    <p><%= @restaurant.address %></p>
    <p><%= @restaurant.phone_number %></p>
  </div>

  <div class="reviews">
    <h4>Reviews</h3>
    <% @restaurant.reviews.each do |review| %>
    <p> <%= review.content %></p>
    <p><%= review.rating %></p>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<h1>Reviews</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content  %>
  <%= f.input :rating  %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>